name: Ingestion

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: "temurin"

      - name: Set up Scala
        uses: olafurpg/setup-scala@v13

      - name: Run Tests
        working-directory: ingestion
        run: sbt test

      - name: Upload Dependency Graph
        uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
        with:
          working-directory: ingestion
